"""Markdown report generation for backtest results."""

from datetime import datetime
from pathlib import Path
from typing import Optional

from .backtest import BacktestResult


def generate_backtest_report(
    result: BacktestResult,
    output_path: Optional[Path] = None,
) -> str:
    """Generate a markdown report from backtest results.

    Args:
        result: BacktestResult from backtester.
        output_path: Optional path to save report. If None, just returns string.

    Returns:
        Markdown formatted report string.
    """
    report = f"""# Backtest Report: {result.symbol}

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Summary

| Metric | Value |
|--------|-------|
| Symbol | {result.symbol} |
| Timeframe | {result.timeframe} |
| Period | {result.start_date.strftime("%Y-%m-%d")} to {result.end_date.strftime("%Y-%m-%d")} |
| Initial Capital | ${result.initial_capital:,.2f} |
| Final Capital | ${result.final_capital:,.2f} |
| **Total Return** | **{result.total_return:+.2f}%** |

## Performance Metrics

| Metric | Value |
|--------|-------|
| Total Trades | {result.total_trades} |
| Winning Trades | {result.winning_trades} |
| Losing Trades | {result.losing_trades} |
| **Win Rate** | **{result.win_rate:.1f}%** |
| Average Win | {result.avg_win:+.2f}% |
| Average Loss | {result.avg_loss:+.2f}% |
| Profit Factor | {result.profit_factor:.2f} |
| Max Drawdown | {result.max_drawdown:.2f}% |
| Sharpe Ratio | {result.sharpe_ratio():.2f} |

## Trade Log

| # | Direction | Entry Time | Entry Price | Exit Time | Exit Price | PnL % |
|---|-----------|------------|-------------|-----------|------------|-------|
"""

    for i, trade in enumerate(result.trades, 1):
        entry_time = (
            trade.entry_time.strftime("%Y-%m-%d %H:%M") if trade.entry_time else "N/A"
        )
        exit_time = (
            trade.exit_time.strftime("%Y-%m-%d %H:%M") if trade.exit_time else "N/A"
        )
        pnl_str = f"{trade.pnl_percent:+.2f}%" if trade.pnl_percent else "N/A"

        report += f"| {i} | {trade.direction.upper()} | {entry_time} | ${trade.entry_price:,.2f} | {exit_time} | ${trade.exit_price:,.2f if trade.exit_price else 0:,.2f} | {pnl_str} |\n"

    report += """
## Notes

- Entry threshold: Score >= 60 (Strong Buy) or Score <= -60 (Strong Sell)
- Exit threshold: Score reverses direction
- Position size: 100% of capital per trade
- Trading fee: 0.1% per trade (applied to both entry and exit)

---

*This report was automatically generated by Trading Signals Backtester.*
"""

    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report)

    return report
